import type {
  Department,
  User,
  Doctor,
  Facility,
  SickLeave,
  Violation,
  Circular,
  Notification,
  UploadedDocument,
  TimelineEvent,
} from '../types';

export const mockDepartments: Department[] = [
  { id: 'dept-1', code: 'FLT-OPS', nameEn: 'Flight Operations', nameAr: 'عمليات الطيران' },
  { id: 'dept-2', code: 'CABIN', nameEn: 'Cabin Crew', nameAr: 'طاقم الضيافة' },
  { id: 'dept-3', code: 'ENG', nameEn: 'Engineering', nameAr: 'الهندسة والصيانة' },
  { id: 'dept-4', code: 'GND-OPS', nameEn: 'Ground Operations', nameAr: 'العمليات الأرضية' },
  { id: 'dept-5', code: 'COM', nameEn: 'Commercial', nameAr: 'التجارية' },
  { id: 'dept-6', code: 'FIN', nameEn: 'Finance', nameAr: 'المالية' },
  { id: 'dept-7', code: 'HR', nameEn: 'Human Resources', nameAr: 'الموارد البشرية' },
  { id: 'dept-8', code: 'IT', nameEn: 'Information Technology', nameAr: 'تكنولوجيا المعلومات' },
  { id: 'dept-9', code: 'SAFE', nameEn: 'Safety & Quality', nameAr: 'السلامة والجودة' },
  { id: 'dept-10', code: 'ADMIN', nameEn: 'Administration', nameAr: 'الإدارة' },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    employeeNumber: 'JA-1247',
    email: 'employee@jordanaviation.jo',
    nameEn: 'Ahmed Al-Ahmad',
    nameAr: 'أحمد الأحمد',
    department: mockDepartments[2],
    jobTitle: 'Maintenance Engineer',
    phone: '0791234567',
    role: 'EMPLOYEE',
    sickLeaveBalance: 8,
    sickLeaveTotal: 14,
  },
  {
    id: 'user-2',
    employeeNumber: 'JA-2051',
    email: 'fatima@jordanaviation.jo',
    nameEn: 'Fatima Hassan',
    nameAr: 'فاطمة حسن',
    department: mockDepartments[1],
    jobTitle: 'Senior Flight Attendant',
    phone: '0792345678',
    role: 'EMPLOYEE',
    sickLeaveBalance: 10,
    sickLeaveTotal: 14,
  },
  {
    id: 'user-3',
    employeeNumber: 'JA-1589',
    email: 'omar@jordanaviation.jo',
    nameEn: 'Omar Khalil',
    nameAr: 'عمر خليل',
    department: mockDepartments[3],
    jobTitle: 'Ground Operations Supervisor',
    phone: '0793456789',
    role: 'EMPLOYEE',
    sickLeaveBalance: 11,
    sickLeaveTotal: 14,
  },
  {
    id: 'user-4',
    employeeNumber: 'JA-3022',
    email: 'sara@jordanaviation.jo',
    nameEn: 'Sara Mahmoud',
    nameAr: 'سارة محمود',
    department: mockDepartments[4],
    jobTitle: 'Sales Manager',
    phone: '0794567890',
    role: 'EMPLOYEE',
    sickLeaveBalance: 13,
    sickLeaveTotal: 14,
  },
  {
    id: 'user-5',
    employeeNumber: 'JA-1100',
    email: 'mohammad@jordanaviation.jo',
    nameEn: 'Mohammad Ali',
    nameAr: 'محمد علي',
    department: mockDepartments[7],
    jobTitle: 'IT Specialist',
    phone: '0795678901',
    role: 'EMPLOYEE',
    sickLeaveBalance: 14,
    sickLeaveTotal: 14,
  },
  {
    id: 'user-6',
    employeeNumber: 'JA-0001',
    email: 'doctor@jordanaviation.jo',
    nameEn: 'Dr. Jalal Al-Khashman',
    nameAr: 'د. جلال الخشمان',
    department: mockDepartments[6],
    jobTitle: 'Company Doctor',
    phone: '0796789012',
    role: 'COMPANY_DOCTOR',
    sickLeaveBalance: 14,
    sickLeaveTotal: 14,
  },
  {
    id: 'user-7',
    employeeNumber: 'JA-0050',
    email: 'admin@jordanaviation.jo',
    nameEn: 'Rania Qasem',
    nameAr: 'رانيا قاسم',
    department: mockDepartments[6],
    jobTitle: 'HR Manager',
    phone: '0797890123',
    role: 'HR_MANAGER',
    sickLeaveBalance: 14,
    sickLeaveTotal: 14,
  },
  {
    id: 'user-8',
    employeeNumber: 'JA-0055',
    email: 'khalid@jordanaviation.jo',
    nameEn: 'Khaled Yousef',
    nameAr: 'خالد يوسف',
    department: mockDepartments[6],
    jobTitle: 'HR Officer',
    phone: '0798901234',
    role: 'HR_OFFICER',
    sickLeaveBalance: 14,
    sickLeaveTotal: 14,
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-1',
    nameEn: 'Dr. Ahmad Saleh',
    nameAr: 'د. أحمد صالح',
    rank: 'SPECIALIST',
    specialty: 'Internal Medicine',
    licenseNumber: 'JM-4521',
    trustScore: 0.88,
    leavesIssued: 12,
    leavesFlagged: 1,
  },
  {
    id: 'doc-2',
    nameEn: 'Dr. Noor Ibrahim',
    nameAr: 'د. نور إبراهيم',
    rank: 'GP',
    specialty: 'General Medicine',
    licenseNumber: 'JM-6789',
    trustScore: 0.75,
    leavesIssued: 8,
    leavesFlagged: 3,
  },
  {
    id: 'doc-3',
    nameEn: 'Dr. Sami Hassan',
    nameAr: 'د. سامي حسن',
    rank: 'CONSULTANT',
    specialty: 'Orthopedics',
    licenseNumber: 'JM-2341',
    trustScore: 0.95,
    leavesIssued: 5,
    leavesFlagged: 0,
  },
  {
    id: 'doc-4',
    nameEn: 'Dr. Reem Khatib',
    nameAr: 'د. ريم خطيب',
    rank: 'SPECIALIST',
    specialty: 'Gastroenterology',
    licenseNumber: 'JM-8821',
    trustScore: 0.82,
    leavesIssued: 7,
    leavesFlagged: 2,
  },
  {
    id: 'doc-5',
    nameEn: 'Dr. Unknown Night Center',
    nameAr: 'طبيب مركز ليلي',
    rank: 'GP',
    specialty: 'General Medicine',
    trustScore: 0.3,
    leavesIssued: 15,
    leavesFlagged: 10,
  },
  {
    id: 'doc-6',
    nameEn: 'Dr. Layla Mahmoud',
    nameAr: 'د. ليلى محمود',
    rank: 'SPECIALIST',
    specialty: 'Neurology',
    licenseNumber: 'JM-9922',
    trustScore: null,
    leavesIssued: 0,
    leavesFlagged: 0,
    isNew: true,
  },
];

export const mockFacilities: Facility[] = [
  {
    id: 'fac-1',
    nameEn: 'Jordan Hospital',
    nameAr: 'مستشفى الأردن',
    type: 'PRIVATE_HOSPITAL',
    trustScore: 0.9,
    leavesFromFacility: 20,
    isBlocked: false,
  },
  {
    id: 'fac-2',
    nameEn: 'Al-Khalidi Hospital',
    nameAr: 'مستشفى الخالدي',
    type: 'PRIVATE_HOSPITAL',
    trustScore: 0.92,
    leavesFromFacility: 15,
    isBlocked: false,
  },
  {
    id: 'fac-3',
    nameEn: 'Prince Hamza Hospital',
    nameAr: 'مستشفى الأمير حمزة',
    type: 'GOVERNMENT_HOSPITAL',
    trustScore: 0.95,
    leavesFromFacility: 10,
    isBlocked: false,
  },
  {
    id: 'fac-4',
    nameEn: 'Royal Medical Services',
    nameAr: 'الخدمات الطبية الملكية',
    type: 'ROYAL_MEDICAL_SERVICES',
    trustScore: 0.97,
    leavesFromFacility: 8,
    isBlocked: false,
  },
  {
    id: 'fac-5',
    nameEn: 'Al-Shifa 24h Center',
    nameAr: 'مركز الشفاء 24 ساعة',
    type: 'PRIVATE_24H',
    trustScore: 0.15,
    leavesFromFacility: 25,
    isBlocked: true,
  },
  {
    id: 'fac-6',
    nameEn: 'Night Care Center',
    nameAr: 'مركز الرعاية الليلية',
    type: 'PRIVATE_24H',
    trustScore: 0.2,
    leavesFromFacility: 18,
    isBlocked: true,
  },
  {
    id: 'fac-7',
    nameEn: 'Zarqa Health Center',
    nameAr: 'مركز صحي الزرقاء',
    type: 'HEALTH_CENTER',
    trustScore: 0.8,
    leavesFromFacility: 4,
    isBlocked: false,
  },
  {
    id: 'fac-8',
    nameEn: 'Ibn Sina Clinic',
    nameAr: 'عيادة ابن سينا',
    type: 'PRIVATE_CLINIC',
    trustScore: null,
    leavesFromFacility: 0,
    isBlocked: false,
    isNew: true,
  },
];

const mockDocuments: UploadedDocument[] = [
  {
    id: 'doc-1',
    fileName: 'sick_leave_certificate.pdf',
    fileSize: 1800000,
    fileType: 'application/pdf',
    url: '/mock/docs/cert.pdf',
    classification: 'SICK_LEAVE_CERTIFICATE',
    confidence: 0.95,
    uploadedAt: new Date('2024-06-12T09:00:00'),
  },
  {
    id: 'doc-2',
    fileName: 'financial_receipt.jpg',
    fileSize: 856000,
    fileType: 'image/jpeg',
    url: '/mock/docs/receipt.jpg',
    classification: 'FINANCIAL_RECEIPT',
    confidence: 0.92,
    uploadedAt: new Date('2024-06-12T09:00:00'),
  },
  {
    id: 'doc-3',
    fileName: 'lab_results.pdf',
    fileSize: 2100000,
    fileType: 'application/pdf',
    url: '/mock/docs/lab.pdf',
    classification: 'LAB_RESULTS',
    confidence: 0.89,
    uploadedAt: new Date('2024-06-12T09:00:00'),
  },
];

const createTimeline = (status: string): TimelineEvent[] => {
  const baseTimeline: TimelineEvent[] = [
    {
      id: 't-1',
      timestamp: new Date('2024-06-12T09:00:00'),
      type: 'SUBMITTED',
      description: 'Submitted by employee',
      color: '#1890ff',
      icon: 'upload',
    },
    {
      id: 't-2',
      timestamp: new Date('2024-06-12T09:02:00'),
      type: 'AI_ANALYZED',
      description: 'Documents analyzed by AI',
      color: '#52c41a',
      icon: 'robot',
    },
  ];

  if (status === 'APPROVED') {
    return [
      ...baseTimeline,
      {
        id: 't-3',
        timestamp: new Date('2024-06-12T10:00:00'),
        type: 'UNDER_REVIEW',
        description: 'Under company doctor review',
        color: '#fa8c16',
        icon: 'eye',
      },
      {
        id: 't-4',
        timestamp: new Date('2024-06-13T09:00:00'),
        type: 'APPROVED',
        description: 'Approved by Dr. Jalal Al-Khashman',
        color: '#52c41a',
        icon: 'check',
      },
      {
        id: 't-5',
        timestamp: new Date('2024-06-13T09:30:00'),
        type: 'EMAIL_SENT',
        description: 'Result email sent',
        color: '#1890ff',
        icon: 'mail',
      },
    ];
  }

  if (status === 'REJECTED') {
    return [
      ...baseTimeline,
      {
        id: 't-3',
        timestamp: new Date('2024-03-15T10:00:00'),
        type: 'UNDER_REVIEW',
        description: 'Under company doctor review',
        color: '#fa8c16',
        icon: 'eye',
      },
      {
        id: 't-4',
        timestamp: new Date('2024-03-15T14:00:00'),
        type: 'REJECTED',
        description: 'Rejected by Dr. Jalal Al-Khashman',
        color: '#ff4d4f',
        icon: 'close',
      },
    ];
  }

  return baseTimeline;
};

export const mockSickLeaves: SickLeave[] = [
  {
    id: 'leave-1',
    refNumber: 'SL-2024-00089',
    employeeId: 'user-1',
    employee: mockUsers[0],
    submittedAt: new Date('2024-06-12T09:00:00'),
    fromDate: new Date('2024-06-12'),
    toDate: new Date('2024-06-13'),
    totalDays: 2,
    status: 'APPROVED',
    doctor: mockDoctors[3],
    facility: mockFacilities[0],
    symptoms: 'Stomach pain, vomiting, diarrhea',
    diagnosis: 'Acute Gastroenteritis',
    icd10Code: 'K52.9',
    employeeComments: 'كان لدي ألم شديد في المعدة منذ ليلة أمس. راجعت الطبيب صباح اليوم.',
    documents: mockDocuments,
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    companyDoctorDecision: 'APPROVED',
    companyDoctorAssessment: 'Diagnosis is consistent with symptoms and lab results show elevated WBC count supporting acute gastroenteritis. All documents are authentic and complete.',
    companyDoctorInstructions: 'Rest for 2 days, stay hydrated, and follow prescribed medication.',
    approvedDays: 2,
    timeline: createTimeline('APPROVED'),
  },
  {
    id: 'leave-2',
    refNumber: 'SL-2024-00088',
    employeeId: 'user-2',
    employee: mockUsers[1],
    submittedAt: new Date('2024-06-10T08:30:00'),
    fromDate: new Date('2024-06-10'),
    toDate: new Date('2024-06-13'),
    totalDays: 4,
    status: 'PARTIALLY_APPROVED',
    doctor: mockDoctors[1],
    facility: mockFacilities[6],
    symptoms: 'Lower back pain',
    diagnosis: 'Back Pain',
    employeeComments: 'ألم في أسفل الظهر منذ 3 أيام.',
    documents: mockDocuments.slice(0, 2),
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    companyDoctorDecision: 'PARTIALLY_APPROVED',
    companyDoctorAssessment: 'General Practitioner can only issue maximum 24 hours (1 day) sick leave per company policy.',
    approvedDays: 1,
    partialApprovalDetails: {
      approvedFrom: new Date('2024-06-10'),
      approvedTo: new Date('2024-06-10'),
      approvedDays: 1,
      rejectedFrom: new Date('2024-06-11'),
      rejectedTo: new Date('2024-06-13'),
      rejectedDays: 3,
      reason: 'GP maximum is 24 hours (1 day). Only 1 day approved per company rules.',
    },
    timeline: createTimeline('PARTIALLY_APPROVED'),
  },
  {
    id: 'leave-3',
    refNumber: 'SL-2024-00087',
    employeeId: 'user-3',
    employee: mockUsers[2],
    submittedAt: new Date('2024-06-17T10:00:00'),
    fromDate: new Date('2024-06-17'),
    toDate: new Date('2024-06-20'),
    totalDays: 4,
    status: 'EXAMINATION_REQUESTED',
    doctor: mockDoctors[0],
    facility: mockFacilities[1],
    symptoms: 'Severe back pain after lifting heavy object',
    diagnosis: 'Lower Back Strain',
    employeeComments: 'حدث الألم بعد رفع صندوق ثقيل في العمل.',
    documents: mockDocuments.slice(0, 2),
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    examinationDetails: {
      date: new Date('2024-06-22'),
      time: '10:00',
      location: 'Company Doctor Clinic, JA HQ, Building 2',
      confirmed: false,
    },
    timeline: [
      ...createTimeline('UNDER_REVIEW'),
      {
        id: 't-exam',
        timestamp: new Date('2024-06-18T14:00:00'),
        type: 'EXAMINATION_REQUESTED',
        description: 'Medical examination requested',
        color: '#eb2f96',
        icon: 'medicine-box',
      },
    ],
  },
  {
    id: 'leave-4',
    refNumber: 'SL-2024-00086',
    employeeId: 'user-1',
    employee: mockUsers[0],
    submittedAt: new Date('2024-05-03T09:00:00'),
    fromDate: new Date('2024-05-03'),
    toDate: new Date('2024-05-03'),
    totalDays: 1,
    status: 'APPROVED',
    doctor: mockDoctors[1],
    facility: mockFacilities[7],
    symptoms: 'Common cold, cough',
    diagnosis: 'Upper Respiratory Tract Infection',
    icd10Code: 'J06.9',
    documents: mockDocuments.slice(0, 2),
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    companyDoctorDecision: 'APPROVED',
    approvedDays: 1,
    timeline: createTimeline('APPROVED'),
  },
  {
    id: 'leave-5',
    refNumber: 'SL-2024-00085',
    employeeId: 'user-4',
    employee: mockUsers[3],
    submittedAt: new Date('2024-05-25T08:00:00'),
    fromDate: new Date('2024-05-25'),
    toDate: new Date('2024-05-26'),
    totalDays: 2,
    status: 'APPROVED',
    doctor: mockDoctors[0],
    facility: mockFacilities[0],
    symptoms: 'Severe headache, sensitivity to light',
    diagnosis: 'Migraine',
    icd10Code: 'G43.9',
    documents: mockDocuments,
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    companyDoctorDecision: 'APPROVED',
    approvedDays: 2,
    timeline: createTimeline('APPROVED'),
  },
  {
    id: 'leave-6',
    refNumber: 'SL-2024-00084',
    employeeId: 'user-1',
    employee: mockUsers[0],
    submittedAt: new Date('2024-03-15T09:00:00'),
    fromDate: new Date('2024-03-15'),
    toDate: new Date('2024-03-16'),
    totalDays: 2,
    status: 'REJECTED',
    doctor: mockDoctors[4],
    facility: mockFacilities[5],
    symptoms: 'Back pain',
    diagnosis: 'Back Pain',
    documents: mockDocuments.slice(0, 2),
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    companyDoctorDecision: 'REJECTED',
    rejectionReason: 'Unapproved facility (24-hour private center)',
    timeline: createTimeline('REJECTED'),
    violationId: 'viol-1',
  },
  {
    id: 'leave-7',
    refNumber: 'SL-2024-00083',
    employeeId: 'user-5',
    employee: mockUsers[4],
    submittedAt: new Date('2024-06-01T11:00:00'),
    fromDate: new Date('2024-06-01'),
    toDate: new Date('2024-06-03'),
    totalDays: 3,
    status: 'UNDER_REVIEW',
    doctor: mockDoctors[0],
    facility: mockFacilities[2],
    symptoms: 'Cough, fever, chest pain',
    diagnosis: 'Acute Bronchitis',
    icd10Code: 'J20.9',
    documents: mockDocuments,
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    timeline: createTimeline('UNDER_REVIEW'),
  },
  {
    id: 'leave-8',
    refNumber: 'SL-2024-00082',
    employeeId: 'user-2',
    employee: mockUsers[1],
    submittedAt: new Date('2024-05-20T07:30:00'),
    fromDate: new Date('2024-05-20'),
    toDate: new Date('2024-05-20'),
    totalDays: 1,
    status: 'APPROVED',
    doctor: mockDoctors[1],
    facility: mockFacilities[6],
    symptoms: 'Headache',
    diagnosis: 'Tension Headache',
    documents: mockDocuments.slice(0, 2),
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    companyDoctorDecision: 'APPROVED',
    approvedDays: 1,
    timeline: createTimeline('APPROVED'),
  },
  {
    id: 'leave-9',
    refNumber: 'SL-2024-00081',
    employeeId: 'user-3',
    employee: mockUsers[2],
    submittedAt: new Date('2024-04-10T09:00:00'),
    fromDate: new Date('2024-04-10'),
    toDate: new Date('2024-04-12'),
    totalDays: 3,
    status: 'DOCS_REQUESTED',
    doctor: mockDoctors[2],
    facility: mockFacilities[1],
    symptoms: 'Knee pain and swelling',
    diagnosis: 'Knee Injury',
    documents: mockDocuments.slice(0, 2),
    wasHospitalized: false,
    isChronicDisease: false,
    companyDoctorId: 'user-6',
    requestedDocuments: ['X-ray results', 'Physical examination report'],
    timeline: [
      ...createTimeline('UNDER_REVIEW'),
      {
        id: 't-docs',
        timestamp: new Date('2024-04-11T10:00:00'),
        type: 'DOCS_REQUESTED',
        description: 'Additional documents requested',
        color: '#722ed1',
        icon: 'file-text',
      },
    ],
  },
  {
    id: 'leave-10',
    refNumber: 'SL-2024-00080',
    employeeId: 'user-4',
    employee: mockUsers[3],
    submittedAt: new Date('2024-06-15T08:00:00'),
    fromDate: new Date('2024-06-15'),
    toDate: new Date('2024-06-15'),
    totalDays: 1,
    status: 'SUBMITTED',
    doctor: mockDoctors[1],
    facility: mockFacilities[6],
    symptoms: 'Stomach pain',
    diagnosis: 'Gastritis',
    documents: mockDocuments.slice(0, 2),
    wasHospitalized: false,
    isChronicDisease: false,
    timeline: [
      {
        id: 't-1',
        timestamp: new Date('2024-06-15T08:00:00'),
        type: 'SUBMITTED',
        description: 'Submitted by employee',
        color: '#1890ff',
        icon: 'upload',
      },
    ],
  },
];

export const mockViolations: Violation[] = [
  {
    id: 'viol-1',
    employeeId: 'user-1',
    leaveId: 'leave-6',
    leave: mockSickLeaves[5],
    date: new Date('2024-03-16'),
    violationType: 'BLOCKED_FACILITY',
    penaltyType: 'SALARY_DEDUCTION',
    penaltyDays: 2,
    description: 'Sick leave from blocked 24-hour private center',
    violationNumber: 1,
  },
];

export const mockCirculars: Circular[] = [
  {
    id: 'cir-1',
    refNumber: 'CIR-2024-001',
    title: 'Updated Sick Leave Policy',
    titleAr: 'تحديث سياسة الإجازات المرضية',
    type: 'POLICY_UPDATE',
    date: new Date('2024-01-01'),
    content: 'Updated sick leave policy effective January 1, 2024...',
    contentAr: 'تحديث سياسة الإجازات المرضية بدءاً من 1 يناير 2024...',
  },
  {
    id: 'cir-2',
    refNumber: 'CIR-2024-005',
    title: 'Al-Shifa Center No Longer Approved',
    titleAr: 'مركز الشفاء غير معتمد بعد الآن',
    type: 'FACILITY_BLACKLIST',
    date: new Date('2024-03-15'),
    content: 'Effective immediately, Al-Shifa 24h Center is no longer approved...',
    contentAr: 'اعتباراً من اليوم، مركز الشفاء 24 ساعة غير معتمد...',
  },
  {
    id: 'cir-3',
    refNumber: 'CIR-2024-008',
    title: 'Reminder: Submit Original Documents',
    titleAr: 'تذكير: تقديم الوثائق الأصلية',
    type: 'REMINDER',
    date: new Date('2024-06-01'),
    content: 'All employees must submit original documents...',
    contentAr: 'يجب على جميع الموظفين تقديم الوثائق الأصلية...',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    title: 'Sick Leave Approved',
    message: 'Your sick leave SL-2024-00089 has been approved',
    type: 'SUCCESS',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: true,
    relatedLeaveId: 'leave-1',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    title: 'Sick Leave Rejected',
    message: 'Your sick leave SL-2024-00084 has been rejected',
    type: 'ERROR',
    timestamp: new Date(Date.now() - 3 * 30 * 24 * 60 * 60 * 1000),
    read: true,
    relatedLeaveId: 'leave-6',
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    title: 'New Company Circular',
    message: 'New company circular: Reminder about documents',
    type: 'INFO',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    read: false,
    relatedCircularId: 'cir-3',
  },
  {
    id: 'notif-4',
    userId: 'user-1',
    title: 'Leave Balance Update',
    message: 'Your sick leave balance: 8 days remaining',
    type: 'INFO',
    timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    read: true,
  },
];

export function getUserLeaves(userId: string): SickLeave[] {
  return mockSickLeaves.filter((leave) => leave.employeeId === userId);
}

export function getUserViolations(userId: string): Violation[] {
  return mockViolations.filter((viol) => viol.employeeId === userId);
}

export function getUserNotifications(userId: string): Notification[] {
  return mockNotifications.filter((notif) => notif.userId === userId);
}

export function getLeaveById(id: string): SickLeave | undefined {
  return mockSickLeaves.find((leave) => leave.id === id);
}

export function getDoctorByName(name: string): Doctor | undefined {
  return mockDoctors.find(
    (doc) => doc.nameEn.toLowerCase().includes(name.toLowerCase()) || doc.nameAr.includes(name)
  );
}

export function getFacilityByName(name: string): Facility | undefined {
  return mockFacilities.find(
    (fac) => fac.nameEn.toLowerCase().includes(name.toLowerCase()) || fac.nameAr.includes(name)
  );
}
